/**
 * slicer-import.test.mjs — leggere un file di slicer, e non mandarlo via.
 *
 * La direttiva pone un vincolo che non è di funzionalità ma di riservatezza:
 * «il parser deve essere locale, NON mandare il file a server esterni». Un
 * G-code contiene la geometria di un pezzo che spesso è il lavoro di un
 * cliente. Qui quel vincolo si verifica come si verifica una regola: il
 * modulo gira in un contesto dove `fetch`, `XMLHttpRequest` e `WebSocket`
 * non esistono, e il sorgente non li nomina.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const src = fs.readFileSync(new URL('../src/product/slicer-import.js', import.meta.url), 'utf8');
const ctx = vm.createContext({ console, TextDecoder, DataView, Uint8Array, Blob, Response });
vm.runInContext(src, ctx);
const S = ctx.InglySlicerImport;

const vicino = (a, b, t = 0.01) => assert.ok(Math.abs(a - b) < t, `${a} ≠ ${b}`);

test('il parser non può contattare nessuno', () => {
  const codice = src.replace(/\/\*[\s\S]*?\*\//g, ' ').split('\n')
    .map((r) => (/^\s*\/\//.test(r) ? '' : r)).join('\n');
  for (const proibito of ['fetch(', 'XMLHttpRequest', 'WebSocket', 'sendBeacon', 'navigator.', 'import(']) {
    assert.ok(!codice.includes(proibito), 'il parser esce dalla pagina: ' + proibito);
  }
});

/* ── PrusaSlicer / OrcaSlicer ──────────────────────────────────────────── */

const PRUSA = `
; generated by PrusaSlicer 2.8.0
G1 X10 Y10
; filament used [g] = 41.25
; total filament used [g] = 48.90
; support filament used [g] = 5.15
; total filament used for wipe tower [g] = 2.50
; total filament cost = 1.22
; estimated printing time (normal mode) = 3h 42m 18s
; filament_type = PLA
`;

test('un G-code PrusaSlicer dà peso, supporti, spurgo, tempo e costo', () => {
  const r = S.daGcode(PRUSA);
  assert.equal(r.ok, true);
  assert.equal(r.formato, 'gcode');
  vicino(r.grammiTotali, 48.90);
  vicino(r.supporti, 5.15);
  vicino(r.purge, 2.50);
  vicino(r.costo, 1.22);
  vicino(r.ore, 3 + 42 / 60 + 18 / 3600);
  /* `deepEqual` fallisce fra realm diversi: gli array vengono da `vm`. */
  assert.equal(r.materiali.join('|'), 'PLA');
});

test('il modello è il totale MENO quel che si butta, mai la somma', () => {
  /* È il doppio conteggio più comune del mestiere: gli slicer dichiarano un
     totale che comprende già supporti e spurgo, e sommarli li paga due volte. */
  const r = S.daGcode(PRUSA);
  vicino(r.grammiModello, 48.90 - 5.15 - 2.50);
  assert.ok(r.grammiModello < r.grammiTotali);
  assert.equal(r.comprendeTutto, true);
});

test('dichiara da quale grafia viene ogni numero', () => {
  const r = S.daGcode(PRUSA);
  assert.ok(r.grafie.peso);
  assert.ok(r.grafie.tempo);
});

/* ── Cura ───────────────────────────────────────────────────────────────── */

test('Cura scrive il tempo in secondi, e viene convertito', () => {
  const r = S.daGcode(';FLAVOR:Marlin\n;TIME:9012\n; total filament used [g] = 12\n');
  assert.equal(r.ok, true);
  vicino(r.ore, 9012 / 3600);
  vicino(r.grammiTotali, 12);
});

/* ── Bambu Studio ───────────────────────────────────────────────────────── */

test('Bambu scrive il peso con un\'altra grafia, e viene letta', () => {
  const r = S.daGcode('; total filament weight [g] : 33.4\n; model printing time: 1h 4m 27s\n');
  assert.equal(r.ok, true);
  vicino(r.grammiTotali, 33.4);
  vicino(r.ore, 1 + 4 / 60 + 27 / 3600);
});

/* ── I casi in cui non si sa ─────────────────────────────────────────────── */

test('un file senza dati di stampa lo dice invece di dare zero', () => {
  const r = S.daGcode('G1 X10 Y10\nG1 X20 Y20\n');
  assert.equal(r.ok, false);
  assert.match(r.motivo, /nessun dato/i);
});

test('un file vuoto non produce un preventivo da zero grammi', () => {
  const r = S.daGcode('');
  assert.equal(r.ok, false);
  assert.equal(r.grammiTotali, 0);
});

test('i numeri con la virgola non diventano numeri diversi', () => {
  /* `parseFloat('48,90')` dà 48: il peso perderebbe i decimali in silenzio. */
  const r = S.daGcode('; total filament used [g] = 48,90\n;TIME:3600\n');
  vicino(r.grammiTotali, 48.90);
});

test('un tempo con i giorni non perde le 24 ore', () => {
  const r = S.oreDa('; estimated printing time (normal mode) = 1d 2h 30m 0s');
  vicino(r.ore, 26.5);
});

test('lo stesso testo dà sempre lo stesso risultato', () => {
  assert.equal(JSON.stringify(S.daGcode(PRUSA)), JSON.stringify(S.daGcode(PRUSA)));
});

test('un peso senza supporti dichiarati non inventa supporti', () => {
  const r = S.daGcode('; total filament used [g] = 20\n;TIME:3600\n');
  assert.equal(r.supporti, 0);
  assert.equal(r.purge, 0);
  vicino(r.grammiModello, 20);
});
